version: '3.8'

services:
  cyber-sec:
    image: ghcr.io/amsoulares/cyber-sec:latest 
    container_name: cyber-sec
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true